"""initial_schema

Revision ID: 4c34fe0b3891
Revises:
Create Date: 2026-03-11 15:11:27.347093

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4c34fe0b3891"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("tiktok_access_token", sa.String(), nullable=False),
        sa.Column("tiktok_open_id", sa.String(), nullable=False),
        sa.Column("phase", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_accounts_account_id"), "accounts", ["account_id"], unique=True)
    op.create_table(
        "agent_decisions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("agent", sa.String(), nullable=False),
        sa.Column("decision_type", sa.String(), nullable=False),
        sa.Column("from_value", sa.String(), nullable=True),
        sa.Column("to_value", sa.String(), nullable=True),
        sa.Column("rationale", sa.String(), nullable=False),
        sa.Column("supporting_data", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_decisions_account_id"),
        "agent_decisions",
        ["account_id"],
        unique=False,
    )
    op.create_table(
        "errors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("agent", sa.String(), nullable=False),
        sa.Column("error_type", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("video_id", sa.String(), nullable=True),
        sa.Column("recovery_suggestion", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("resolved_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_errors_account_id"), "errors", ["account_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("niche", sa.String(), nullable=False),
        sa.Column("product_name", sa.String(), nullable=False),
        sa.Column("product_url", sa.String(), nullable=False),
        sa.Column("commission_rate", sa.Float(), nullable=False),
        sa.Column("sales_velocity_score", sa.Float(), nullable=False),
        sa.Column("cached_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_products_account_id"), "products", ["account_id"], unique=False)
    op.create_table(
        "video_metrics",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("video_id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("recorded_at", sa.DateTime(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("share_count", sa.Integer(), nullable=False),
        sa.Column("average_time_watched", sa.Float(), nullable=False),
        sa.Column("retention_3s", sa.Float(), nullable=False),
        sa.Column("retention_15s", sa.Float(), nullable=False),
        sa.Column("fyp_reach_pct", sa.Float(), nullable=False),
        sa.Column("affiliate_clicks", sa.Integer(), nullable=False),
        sa.Column("affiliate_orders", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_video_metrics_video_id_recorded_at",
        "video_metrics",
        ["video_id", "recorded_at"],
        unique=False,
    )
    op.create_table(
        "videos",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("niche", sa.String(), nullable=False),
        sa.Column("hook_archetype", sa.String(), nullable=True),
        sa.Column("lifecycle_state", sa.String(), nullable=False),
        sa.Column("script_text", sa.String(), nullable=True),
        sa.Column("voiceover_path", sa.String(), nullable=True),
        sa.Column("assembled_video_path", sa.String(), nullable=True),
        sa.Column("tiktok_video_id", sa.String(), nullable=True),
        sa.Column("affiliate_link", sa.String(), nullable=True),
        sa.Column("product_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("posted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.account_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_videos_account_id"), "videos", ["account_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_videos_account_id"), table_name="videos")
    op.drop_table("videos")
    op.drop_index("ix_video_metrics_video_id_recorded_at", table_name="video_metrics")
    op.drop_table("video_metrics")
    op.drop_index(op.f("ix_products_account_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_errors_account_id"), table_name="errors")
    op.drop_table("errors")
    op.drop_index(op.f("ix_agent_decisions_account_id"), table_name="agent_decisions")
    op.drop_table("agent_decisions")
    op.drop_index(op.f("ix_accounts_account_id"), table_name="accounts")
    op.drop_table("accounts")
    # ### end Alembic commands ###
