"""add_paused_agent_queues_to_accounts

Revision ID: bce9f4774513
Revises: 0b18d822ca2d
Create Date: 2026-03-14 17:10:34.838717

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bce9f4774513"
down_revision: Union[str, None] = "0b18d822ca2d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("accounts", sa.Column("paused_agent_queues", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("accounts", "paused_agent_queues")
    # ### end Alembic commands ###
