"""add_eliminated_to_products

Revision ID: c43d77205a57
Revises: 4c34fe0b3891
Create Date: 2026-03-11 19:54:56.301777

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c43d77205a57'
down_revision: Union[str, None] = '4c34fe0b3891'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Backfill: product_id was in ORM model but missing from initial migration
    op.add_column('products', sa.Column(
        'product_id', sa.String(), nullable=False, server_default=sa.text("''"),
    ))

    op.add_column('products', sa.Column(
        'eliminated', sa.Boolean(), nullable=False, server_default=sa.text('false'),
    ))
    op.create_index(op.f('ix_products_product_id'), 'products', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_product_id'), table_name='products')
    op.drop_column('products', 'eliminated')
    op.drop_column('products', 'product_id')
    # ### end Alembic commands ###
